# Generated by Django 6.0.3 on 2026-03-06 09:36

import django.db.models.deletion
import file_storage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='file_storage.folder', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'unique_together': {('name', 'parent_folder', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=file_storage.models.user_file_upload_path, verbose_name='Файл')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('original_name', models.CharField(editable=False, max_length=255, verbose_name='Оригинальное название')),
                ('size', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Размер')),
                ('content_type', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Тип')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file_storage.folder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен доступа')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Скачиваний')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Последний доступ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shares', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='file_storage.file', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Расшаривание',
                'verbose_name_plural': 'Расшаривания',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['share_token'], name='file_storag_share_t_1999d3_idx')],
            },
        ),
    ]
