# Generated by Django 6.0.3 on 2026-03-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='file',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
