# Generated by Django 6.0.3 on 2026-03-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_file_downloads_count_file_last_downloaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesharing',
            name='downloads_count',
        ),
        migrations.RemoveField(
            model_name='filesharing',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='filesharing',
            name='views_count',
        ),
    ]
